# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache 2.0 license.  See the LICENSE file in the project root for terms

version: 4
shared:
    environment:
        PACKAGE_DIR: src
        PACKAGE_DIRECTORY: src

jobs:
    validate_codestyle:
        template: python/validate_codestyle
        requires: [~commit, ~pr]

    validate_dependencies:
        template: python/validate_dependencies
        requires: [~commit, ~pr]

    validate_lint:
        template: python/validate_lint
        requires: [~commit, ~pr]

    validate_security:
        template: python/validate_security
        requires: [~commit, ~pr]

    validate_test:
        template: python/validate_unittest
        steps:
            - postupdate_version: |
                PACKAGE_VERSION="`meta get package.version`"
                echo $PACKAGE_VERSION
            - postvalidate_code: meta set package.version "$PACKAGE_VERSION"
        requires: [~commit, ~pr]

    validate_type:
        template: python/validate_type
        requires: [~commit, ~pr]

    validate_documentation:
        environment:
            BASE_PYTHON: /opt/python/cp37-cp37m/bin/python3
            DOCUMENTATION_DEBUG: False
            DOCUMENTATION_FORMATS: mkdocs
            DOCUMENTATION_PUBLISH: False
        image: quay.io/pypa/manylinux2010_x86_64
        steps:
            - bootstrap_python: sd-cmd exec python/python_bootstrap@stable
            - install_local_package: $BASE_PYTHON -m pip install .
            - publish_documentation: $BASE_PYTHON -m screwdrivercd.documentation
        requires: [dependency_validation, style_validation, lint_validation, type_validation, security_validation, test_validation, version]

    generate_version:
        template: python/generate_version
        requires: [~commit, ~pr]

    publish_test_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
            TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        requires: [generate_version, validate_test, validate_lint, validate_codestyle, validate_dependencies, validate_security, validate_type]

    verify_test_package:
        template: python/validate_pypi_package
        environment:
            PYPI_INDEX_URL: https://test.pypi.org/simple
        steps:
            - update_version: |
                PACKAGE_VERSION="`meta get package.version`"
                echo $PACKAGE_VERSION
            # - postvalidate_code: meta set package.version "$PACKAGE_VERSION"
        requires: [publish_test_pypi]

    publish_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
        requires: [verify_test_package]
