# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache 2.0 license.  See the LICENSE file in the project root for terms

version: 4
shared:
  environment:
    PACKAGE_DIRECTORY: src/screwdrivercd
  steps:
    - update_version: |
      $BASE_PYTHON -m pip install .
      screwdrivercd_version

jobs:
  validate_test:
    template: python/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  validate_safetydb:
    template: python/validate_safety
    requires: [~commit, ~pr]

  validate_security:
    template: python/validate_security
    requires: [~commit, ~pr]

  generate_version:
    template: python/generate_version
    steps:
      - generate_version: |
        $BASE_PYTHON -m pip install .
        screwdrivercd_version --ignore_meta --update_meta
    requires: [~commit]

  publish_test_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, validate_safetydb, validate_security,  generate_version]

  verify_test_package:
    template: python/validate_pypi_package
    environment:
      PYPI_INDEX_URL: https://test.pypi.org/simple
    requires: [publish_test_pypi]

  publish_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
    requires: [verify_test_package]
